---
on:
  workflow_call:
    inputs:
      runs_on:
        description: "The operating system used for the runner"
        required: false
        default: "ubuntu-latest"
        type: "string"
      flags:
        description: "Additional flags to pass to matrix_from_metadata_v3"
        required: false
        default: ''
        type: "string"
    outputs:
      spec_matrix:
        description: "Spec matrix from metadata"
        value: ${{ jobs.generate.outputs.spec_matrix }}
      acceptance_matrix:
        description: "Acceptance matrix from metadata"
        value: ${{ jobs.generate.outputs.acceptance_matrix }}

jobs:
  generate:
    name: Generate
    runs-on: ${{ inputs.runs_on }}
    outputs:
      spec_matrix: ${{ steps.get-matrix.outputs.spec_matrix }}
      acceptance_matrix: ${{ steps.get-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Activate Ruby 3.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true

      - name: Matrix from Metadata
        id: get-matrix
        run: |
          bundle exec matrix_from_metadata_v3 ${{ inputs.flags }}
